-- CreateTable
CREATE TABLE "PlatformSettings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "siteName" TEXT NOT NULL DEFAULT 'Lurevia',
    "siteTagline" TEXT NOT NULL DEFAULT 'Artisanat malgache authentique',
    "siteDescription" TEXT NOT NULL DEFAULT 'Découvrez l''artisanat malgache fait main',
    "contactEmail" TEXT NOT NULL DEFAULT 'contact@lurevia.mg',
    "contactPhone" TEXT NOT NULL DEFAULT '+261 34 12 345 67',
    "contactAddress" TEXT NOT NULL DEFAULT 'Antananarivo, Madagascar',
    "defaultCurrency" TEXT NOT NULL DEFAULT 'MGA',
    "logoUrl" TEXT,
    "faviconUrl" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#2F7BF6',
    "secondaryColor" TEXT NOT NULL DEFAULT '#0A1B3D',
    "accentColor" TEXT NOT NULL DEFAULT '#E8A33D',
    "facebookUrl" TEXT,
    "instagramUrl" TEXT,
    "tiktokUrl" TEXT,
    "whatsappNumber" TEXT,
    "linkedinUrl" TEXT,
    "privacyPolicy" TEXT NOT NULL DEFAULT '',
    "termsOfService" TEXT NOT NULL DEFAULT '',
    "cookieMessage" TEXT NOT NULL DEFAULT 'Nous utilisons des cookies pour améliorer votre expérience.',
    "legalCompanyName" TEXT NOT NULL DEFAULT 'Lurevia SARL',
    "legalRegistrationNumber" TEXT,
    "freeShippingThreshold" INTEGER NOT NULL DEFAULT 250000,
    "defaultShippingCost" INTEGER NOT NULL DEFAULT 8000,
    "enableMVola" BOOLEAN NOT NULL DEFAULT true,
    "enableCOD" BOOLEAN NOT NULL DEFAULT true,
    "enableCard" BOOLEAN NOT NULL DEFAULT false,
    "enableBankTransfer" BOOLEAN NOT NULL DEFAULT false,
    "mvolaMerchantNumber" TEXT,
    "codMaxAmount" INTEGER,
    "notifyOnNewOrder" BOOLEAN NOT NULL DEFAULT true,
    "notifyOnNewReview" BOOLEAN NOT NULL DEFAULT true,
    "notifyOnLowStock" BOOLEAN NOT NULL DEFAULT true,
    "lowStockThreshold" INTEGER NOT NULL DEFAULT 5,
    "sendOrderConfirmation" BOOLEAN NOT NULL DEFAULT true,
    "sendShippingNotification" BOOLEAN NOT NULL DEFAULT true,
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "maintenanceMessage" TEXT NOT NULL DEFAULT '',
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedBy" UUID,

    CONSTRAINT "PlatformSettings_pkey" PRIMARY KEY ("id")
);
