import { Router } from "express";
import { requireAuth, requireRole, requireVerified } from "../../../middlewares/auth.middleware";
import { validate } from "../../../middlewares/validate.middleware";
import { sellerController } from "../controller/seller.controller";
import { applySellerSchema, createProductSchema, productDeletionRequestSchema, publicSellerIdSchema, publicSellerListSchema, sellerListSchema, sellerProductIdSchema, sellerStatusSchema, updateProductSchema, updateSellerProfileSchema } from "../dto";
import { financialController } from "../../financial/controller/financial.controller";
import { createContractSchema } from "../../financial/validator/financial.validator";

const router = Router();
router.get("/public", validate({ query: publicSellerListSchema }), sellerController.publicProfiles);
router.get("/public/:id", validate({ params: publicSellerIdSchema }), sellerController.publicProfile);
router.post("/public/:id/subscribe", requireAuth, validate({ params: publicSellerIdSchema }), sellerController.subscribe);
router.delete("/public/:id/subscribe", requireAuth, validate({ params: publicSellerIdSchema }), sellerController.unsubscribe);
router.post("/apply", requireAuth, requireVerified, validate({ body: applySellerSchema }), sellerController.apply);
router.use(requireAuth, requireRole("SELLER"), requireVerified);
router.get("/profile", sellerController.myProfile);
router.patch("/profile", validate({ body: updateSellerProfileSchema }), sellerController.updateProfile);
router.post("/contracts", validate({ body: createContractSchema }), financialController.createContract);
router.get("/stats", sellerController.stats);
router.get("/feedback", sellerController.feedback);
router.get("/products", validate({ query: sellerListSchema }), sellerController.products);
router.post("/products", validate({ body: createProductSchema }), sellerController.createProduct);
router.patch("/products/:id", validate({ params: sellerProductIdSchema, body: updateProductSchema }), sellerController.updateProduct);
router.post("/products/:id/deletion-request", validate({ params: sellerProductIdSchema, body: productDeletionRequestSchema }), sellerController.requestProductDeletion);
router.delete("/products/:id", validate({ params: sellerProductIdSchema }), sellerController.removeProduct);
router.get("/orders", validate({ query: sellerListSchema }), sellerController.orders);
router.get("/orders/:id", validate({ params: sellerProductIdSchema }), sellerController.order);
router.patch("/orders/:id/status", validate({ params: sellerProductIdSchema, body: sellerStatusSchema }), sellerController.status);
export default router;
